[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
rehearsal_guard = "TSjcyXhvjYT9wVNcGehoYNCZavry7rmMhkbukhmDxiE"
rehearsal_earn = "FDkUBYhiH45BJd4svgHFw8tjSdrYVabcJhenpo81AsjV"

[programs.localnet]
rehearsal_guard = "TSjcyXhvjYT9wVNcGehoYNCZavry7rmMhkbukhmDxiE"
rehearsal_earn = "FDkUBYhiH45BJd4svgHFw8tjSdrYVabcJhenpo81AsjV"

[provider]
cluster = "devnet"
wallet = "./keys/deployer.json"

[scripts]
test = "true"
